### ISSUE TITLE
The length of substring can't be longer than '266' which is the length of the source string

### ISSUE THREAD

**Issue by acieslik** [alex-mcla/FlowDetails#1]
The output of "Set ConnectionStr" is:
{"shared_commondataserviceforapps":{"runtimeSource":"embedded","connection":{"connectionReferenceLogicalName":"ak_MicrosoftDataverseKaercherCustomerCareRelease742Flows"},"api":{"name":"shared_commondataserviceforapps"}},"shared_commondataserviceforapps-2":{"runtimeSource":"embedded","connection":{"connectionReferenceLogicalName":"ak_sharedcommondataserviceforapps_72ce4"},"api":{"name":"shared_commondataserviceforapps"}}}

varConnectionsThisFlow is empty array initially

In beginning of the second iteration of "Do until no more occurences of connectionReferenceLogicalName" loop 
the variable "varConnectionStr" contains:
e742Flows"},"api":{"name":"shared_commondataserviceforapps"}},"shared_commondataserviceforapps-2":{"runtimeSource":"embedded","connection":{"connectionReferenceLogicalName":"ak_sharedcommondataserviceforapps_72ce4"},"api":{"name":"shared_commondataserviceforapps"}}}

And then the condition "If Connection not already in list" will fail with error:
The length of substring can't be longer than '266' which is the length of the source string
![grafik](https://github.com/alex-mcla/FlowDetails/assets/3213497/43522578-f1e3-43bf-a7df-9be8b3afcc0a)

I assume the substring function fails here, because the fixed length of 33 or 80 and so on can cause a problem:
substring(variables('varConnectionStr'),add(33,indexOf(variables('varConnectionStr'),'connectionReferenceLogicalName')),
          sub(indexOf(variables('varConnectionStr'),'"},"api"'),
              add(33,indexOf(variables('varConnectionStr'),'connectionReferenceLogicalName'))))

**Comment by alex-mcla** [comment]
@acieslik thanks for notifying me of the issue. Would you be OK to send me the raw outputs of the 'Set ConnectionStr' step (just above the 'If Connection String contains Logical Name' step)? This will help me to debug.

**Comment by alex-mcla** [comment]
@acieslik many thanks for the details you gave, and apologies for not realising on first reading. I've now corrected the issue. Your suggestion of the fixed length 80 was correct. You example, validly, used a very long connection name, which resulted in the error. There's now an additional compose that works out the correct length to get beyond where 'api' is. The 33 is correct, as that the length of 'connectionReferenceLogicalName'.

The updated solutions are available.
